; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
;default_envs = knx2hovalgateway_develop
extra_configs=
    lib/OGM-Common/platformio.base.ini
    lib/OGM-Common/platformio.samd.ini
    lib/OGM-Common/platformio.rp2040.ini


[common]
extends = BASE, KNX_TP
monitor_speed = 115200 
; required for all the envs
lib_deps =
	#seeed-studio/CAN_BUS_Shield@^2.3.3
	# https://github.com/Seeed-Studio/Seeed_Arduino_CAN.git
	https://github.com/Blizzard26/Seeed_Arduino_CAN
build_flags =
    ${BASE.build_flags}
    ${KNX_TP.build_flags}


[seeed_xiao_rp2040]
extends = RP2040, common
monitor_speed = 115200 
platform=${RP2040.platform}
#platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = seeed_xiao_rp2040
framework = arduino
lib_deps = 
	${common.lib_deps}
	; gitlab-konnekting/KonnektingFlashStorage@^1.0.1
build_flags = 
    ${common.build_flags}
    ${RP2040_FLASH.build_flags}
    -D SERIAL_DEBUG=Serial

[knx2hovalgateway_base_rp2040]
extends = seeed_xiao_rp2040
build_flags = 
    ${seeed_xiao_rp2040.build_flags}
    ;-D OPENKNX_DUALCORE

[env:knx2hovalgateway_dev]
extends = knx2hovalgateway_base_rp2040
build_flags = 
    ${knx2hovalgateway_base_rp2040.build_flags}
    -D OPENKNX_WAIT_FOR_SERIAL=5000
    -D OPENKNX_DEBUG
    ;"-D OPENKNX_TRACE1=.*"
    ;"-D OPENKNX_TRACE1=Common.*"
    ;"-D OPENKNX_TRACE2=Flash.*"


[env:knx2hovalgateway_release]
extends = knx2hovalgateway_base_rp2040
build_flags = 
    ${knx2hovalgateway_base_rp2040.build_flags}
    -D OPENKNX_WATCHDOG